# This is a template for SealedSecrets
# To generate: make seal-secret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: primeclean-secrets
  namespace: primeclean
spec:
  encryptedData:
    STRIPE_SECRET_KEY: AgBy3F4O...
    XERO_CLIENT_ID: AgBy3F4O...
    XERO_CLIENT_SECRET: AgBy3F4O...
    OPENAI_API_KEY: AgBy3F4O...
  template:
    metadata:
      name: primeclean-secrets
      namespace: primeclean
    type: Opaque
